name: certora-bug-injection

on:
  pull_request:
    branches:
      - certora

  workflow_dispatch:

jobs:

  list-patches:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo ::set-output name=matrix::$(ls certora/tests/certora/*.patch | jq -Rsc 'split("\n")[:-1]')

  verify:
    runs-on: ubuntu-latest
    needs: 
        - list-patches
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Check key
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
        run: echo "key length" ${#CERTORAKEY}

      - name: Install python
        uses: actions/setup-python@v2
        with: { python-version: 3.9 }

      - name: Install java
        uses: actions/setup-java@v1
        with: { java-version: "11", java-package: jre }

      - name: Install certora cli
        run: pip3 install certora-cli==3.6.8.post3
      
      - name: Install solc
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.10/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.10

      - name: Verify rule ${{ matrix.rule }}
        run: |
          git apply --allow-empty ${{ matrix.patch }}
          certoraRun ${{ matrix.rule }}
          
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
          
    strategy:
      fail-fast: false
      max-parallel: 16
      matrix:
        patch: ${{ fromJson(needs.list-patches.outputs.matrix) }} 
        rule: 
            - certora/conf/verify_erc4626_verified.conf --rules erc4626_1verified
            - certora/conf/verify_erc4626_verified.conf --rules erc4626_2verified erc4626_3verified
            - certora/conf/verify_staticatokenlm_verified.conf --rules SAT1verified SAT2verified
            - certora/conf/verify_staticatokenlm_verified.conf --rules SAT3verified
            